// client/src/pages/FreeRound.tsx
import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { useGame } from '@/contexts/GameContext';
import { useSocket } from '@/hooks/useSocket';
import { DragDropZone } from '@/components/DragDropZone';

export default function FreeRound() {
  const [, setLocation] = useLocation();
  const { state, dispatch } = useGame();
  const { toast } = useToast();
  const { on, emit } = useSocket(state.roomCode || undefined);

  const [timeRemaining, setTimeRemaining] = useState(180); // 3 minutes
  const [playersReady, setPlayersReady] = useState<string[]>([]);

  useEffect(() => {
    if (!state.roomCode || state.status !== 'FREE_ROUND') {
      setLocation('/game');
      return;
    }

    // Timer countdown
    const timer = setInterval(() => {
      setTimeRemaining(prev => {
        if (prev <= 1) {
          clearInterval(timer);
          showResults();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    // Socket event listeners
    const unsubscribers = [
      on('situation:moved', (data: any) => {
        dispatch({
          type: 'UPDATE_SITUATION_POSITION',
          payload: { id: data.situationId, position: data.position }
        });
      }),

      on('player:ready', (data: any) => {
        setPlayersReady(prev => {
          if (!prev.includes(data.playerId)) {
            return [...prev, data.playerId];
          }
          return prev;
        });
      }),

      on('results:ready', () => {
        dispatch({ type: 'SET_STATUS', payload: 'SHOW_RESULTS' });
        setLocation('/results');
      }),

      on('drag:move:update', (data: any) => {
        emit('mouse:move', { x: data.x, y: data.y, playerId: state.playerId });
      }),
    ];

    return () => {
      clearInterval(timer);
      unsubscribers.forEach(unsub => unsub());
    };
  }, [state.roomCode, state.status]);

  const handlePositionUpdate = async (situationId: string, position: number) => {
    try {
      await apiRequest('PUT', `/api/situations/${situationId}/position`, {
        position,
        roomCode: state.roomCode,
      });

      emit('drag:move', {
        elementId: situationId,
        x: position,
        y: 0,
        playerId: state.playerId,
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update position",
        variant: "destructive",
      });
    }
  };

  const markPlayerReady = () => {
    if (!playersReady.includes(state.playerId!)) {
      setPlayersReady(prev => [...prev, state.playerId!]);
      emit('player:ready', { playerId: state.playerId });
    }
  };

  const showResults = async () => {
    try {
      await apiRequest('POST', `/api/games/${state.roomCode}/results`);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to show results",
        variant: "destructive",
      });
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const allPlayersReady = playersReady.length === state.players.length;
  const isPlayerReady = playersReady.includes(state.playerId!);

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-purple-900">
      {/* Header */}
      <header className="bg-white/10 backdrop-blur-md border-b border-white/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between py-4">
            <div className="flex items-center space-x-6">
              <h1 className="text-xl font-bold text-white">Free-Hand Round</h1>
              <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg px-4 py-2">
                <span className="text-yellow-400 font-medium">Collaborative Phase</span>
              </div>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="text-white/70">
                <i className="fas fa-clock mr-2"></i>
                <span className="font-mono">{formatTime(timeRemaining)}</span> remaining
              </div>
              <div className="text-white/70">
                <span>{playersReady.length}</span> of <span>{state.players.length}</span> ready
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Instructions */}
        <Card className="bg-yellow-500/10 border-yellow-500/20 mb-8">
          <CardContent className="p-6">
            <div className="flex items-start">
              <div className="bg-yellow-500/20 p-2 rounded-lg mr-4">
                <i className="fas fa-info text-yellow-400"></i>
              </div>
              <div>
                <h3 className="font-semibold text-yellow-400 mb-2">Collaborative Adjustment Phase</h3>
                <p className="text-slate-300">
                  Now everyone can move their own situation to better fit the sequence. Work together to create the most logical order!
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Enhanced Sequence Area */}
        <Card className="bg-white/10 backdrop-blur-md border-white/20">
          <CardHeader>
            <CardTitle className="text-white flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <i className="fas fa-hands"></i>
                <span>Adjust the Sequence</span>
              </div>
              <div className="flex items-center space-x-2 text-sm text-slate-400">
                <span>0 (Low)</span>
                <div className="w-16 h-px bg-gradient-to-r from-green-400 to-red-400"></div>
                <span>100 (High)</span>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <DragDropZone
              situations={state.situations}
              onPositionUpdate={handlePositionUpdate}
              currentPlayerId={state.playerId}
              canEdit={true}
              isFreeRound={true}
            />

            {/* Player status */}
            <div className="flex justify-between items-center mt-6">
              <div className="flex items-center space-x-4">
                {state.players.map((player) => {
                  const isReady = playersReady.includes(player.id);
                  return (
                    <div key={player.id} className="flex items-center">
                      <div
                        className="w-3 h-3 rounded-full mr-2"
                        style={{ backgroundColor: player.color }}
                      ></div>
                      <span className="text-sm text-white">{player.name}</span>
                      {isReady ? (
                        <i className="fas fa-check text-green-400 ml-2"></i>
                      ) : (
                        <i className="fas fa-hourglass-half text-yellow-400 ml-2"></i>
                      )}
                    </div>
                  );
                })}
              </div>
              
              <div className="flex items-center space-x-4">
                {!isPlayerReady && (
                  <Button
                    onClick={markPlayerReady}
                    className="bg-green-500 hover:bg-green-500/90"
                  >
                    <i className="fas fa-check mr-2"></i>
                    I'm Ready
                  </Button>
                )}
                
                {(state.isHost && allPlayersReady) || timeRemaining === 0 ? (
                  <Button
                    onClick={showResults}
                    className="bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600"
                  >
                    <i className="fas fa-trophy mr-2"></i>
                    Show Results
                  </Button>
                ) : (
                  <Badge variant="outline" className="text-white border-white/20">
                    Waiting for all players...
                  </Badge>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Real-time Activity Feed */}
        <Card className="bg-white/5 backdrop-blur-md border-white/10 mt-6">
          <CardHeader>
            <CardTitle className="text-white text-sm flex items-center space-x-2">
              <i className="fas fa-broadcast-tower"></i>
              <span>Live Activity</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2 text-sm max-h-24 overflow-y-auto">
              <div className="flex items-center space-x-2 text-slate-400">
                <div className="w-2 h-2 bg-primary rounded-full"></div>
                <span>Players are actively positioning their situations...</span>
                <span className="text-xs">Live</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}

// src/app/pages/free-round/free-round.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { GameService } from '../../services/game.service';
import { SocketService } from '../../services/socket.service';
import { GameState, SituationWithPlayer } from '../../models/game.models';

@Component({
  selector: 'app-free-round',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-4">
      <div class="max-w-6xl mx-auto">
        <!-- Header -->
        <div class="flex justify-between items-center mb-8">
          <div>
            <h1 class="text-3xl font-bold text-white mb-2">Free Round</h1>
            <p class="text-slate-400">Collaborate to arrange all situations together</p>
          </div>
          <div class="text-right">
            <div class="bg-slate-800 px-4 py-2 rounded-lg mb-2">
              <span class="text-slate-400 text-sm">Room:</span>
              <span class="text-white font-mono font-bold ml-2">{{ gameState.roomCode }}</span>
            </div>
            <div class="flex items-center text-green-400" *ngIf="connected">
              <i class="fas fa-circle text-xs mr-2"></i>
              <span class="text-sm">Connected</span>
            </div>
          </div>
        </div>

        <!-- Instructions -->
        <div class="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 mb-8">
          <div class="flex items-center text-blue-400 mb-2">
            <i class="fas fa-info-circle mr-2"></i>
            <span class="font-medium">Free Round</span>
          </div>
          <p class="text-blue-300 text-sm">
            Now everyone can see and rearrange all situations. Work together to find the best order before revealing the results!
          </p>
        </div>

        <!-- Collaborative Drag and Drop Area -->
        <div class="bg-slate-800/50 border border-slate-700 rounded-lg p-6">
          <div class="flex justify-between items-center mb-6">
            <h3 class="text-xl font-semibold text-white">Arrange All Situations</h3>
            <div class="text-slate-400 text-sm">
              Everyone can drag and rearrange
            </div>
          </div>

          <!-- Scale -->
          <div class="relative mb-8">
            <div class="flex justify-between text-slate-400 text-sm mb-2">
              <span>0</span>
              <span>25</span>
              <span>50</span>
              <span>75</span>
              <span>100</span>
            </div>
            <div class="h-2 bg-gradient-to-r from-blue-500 via-yellow-500 to-red-500 rounded-full"></div>
          </div>

          <!-- Drop Zone -->
          <div 
            class="min-h-96 border-2 border-dashed border-slate-600 rounded-lg p-4 relative"
            (dragover)="onDragOver($event)"
            (drop)="onDrop($event)"
          >
            <div class="grid grid-cols-1 gap-4">
              <div 
                *ngFor="let situation of sortedSituations; let i = index"
                class="situation-card bg-slate-700 border border-slate-600 rounded-lg p-4 cursor-move transition-all hover:border-slate-500"
                [class.opacity-50]="draggedItem?.id === situation.id"
                [class.ring-2]="situation.playerId === gameState.playerId"
                [class.ring-primary]="situation.playerId === gameState.playerId"
                draggable="true"
                (dragstart)="onDragStart($event, situation)"
                (dragend)="onDragEnd($event)"
              >
                <div class="flex items-center justify-between">
                  <div class="flex items-center space-x-3">
                    <div 
                      class="w-4 h-4 rounded-full"
                      [style.background-color]="situation.player.color"
                    ></div>
                    <div class="flex-1">
                      <p class="text-white font-medium">{{ situation.content }}</p>
                      <div class="flex items-center space-x-2 text-slate-400 text-sm">
                        <span>by {{ situation.player.name }}</span>
                        <span *ngIf="situation.playerId === gameState.playerId" class="text-primary">
                          (Your situation)
                        </span>
                      </div>
                    </div>
                  </div>
                  <div class="flex items-center space-x-2">
                    <span class="text-slate-400 text-sm">#{{ i + 1 }}</span>
                    <i class="fas fa-grip-vertical text-slate-400"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Show Results Button (Host Only) -->
          <div class="mt-6 text-center" *ngIf="gameState.isHost">
            <button 
              (click)="showResults()"
              [disabled]="isShowingResults"
              class="bg-green-500 hover:bg-green-500/90 text-white font-medium py-3 px-8 rounded-md transition-colors disabled:opacity-50"
            >
              <span *ngIf="isShowingResults">
                <i class="fas fa-spinner fa-spin mr-2"></i>
                Loading Results...
              </span>
              <span *ngIf="!isShowingResults">Show Results</span>
            </button>
          </div>

          <!-- Waiting for Host -->
          <div class="mt-6 text-center" *ngIf="!gameState.isHost">
            <div class="text-slate-400">
              <i class="fas fa-clock mr-2"></i>
              Waiting for host to show results...
            </div>
          </div>
        </div>

        <!-- Players Activity -->
        <div class="mt-8 bg-slate-800/30 border border-slate-700 rounded-lg p-6">
          <h3 class="text-lg font-semibold text-white mb-4">Players</h3>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div 
              *ngFor="let player of gameState.players"
              class="flex items-center space-x-2"
            >
              <div 
                class="w-3 h-3 rounded-full"
                [style.background-color]="player.color"
              ></div>
              <span class="text-white text-sm">{{ player.name }}</span>
              <span 
                *ngIf="player.isHost"
                class="text-primary text-xs"
              >
                (Host)
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .text-primary { color: hsl(263 70% 50%); }
    .ring-primary { --tw-ring-color: hsl(263 70% 50%); }
    .situation-card:hover { transform: translateY(-2px); }
  `]
})
export class FreeRoundComponent implements OnInit, OnDestroy {
  gameState!: GameState;
  connected = false;
  isShowingResults = false;
  draggedItem: SituationWithPlayer | null = null;
  
  private subscriptions = new Subscription();

  constructor(
    private gameService: GameService,
    private socketService: SocketService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.subscriptions.add(
      this.gameService.gameState$.subscribe(state => {
        this.gameState = state;
        if (!state.roomCode || state.status !== 'FREE_ROUND') {
          this.router.navigate(['/']);
          return;
        }
        
        if (state.status === 'SHOW_RESULTS') {
          this.router.navigate(['/results']);
        }
      })
    );

    this.subscriptions.add(
      this.socketService.connected$.subscribe(connected => {
        this.connected = connected;
      })
    );

    // Listen for position updates
    this.subscriptions.add(
      this.socketService.on('situationPositionUpdated').subscribe((data: any) => {
        const situations = this.gameState.situations.map(s => 
          s.id === data.situationId ? { ...s, position: data.position } : s
        );
        this.gameService.updateGameState({ situations });
      })
    );

    this.subscriptions.add(
      this.socketService.on('resultsReady').subscribe(() => {
        this.gameService.updateGameState({ status: 'SHOW_RESULTS' });
      })
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  get sortedSituations(): SituationWithPlayer[] {
    return [...this.gameState.situations].sort((a, b) => a.position - b.position);
  }

  onDragStart(event: DragEvent, situation: SituationWithPlayer): void {
    this.draggedItem = situation;
    if (event.dataTransfer) {
      event.dataTransfer.setData('text/plain', situation.id);
    }
  }

  onDragEnd(event: DragEvent): void {
    this.draggedItem = null;
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    if (!this.draggedItem) return;

    const dropZone = event.currentTarget as HTMLElement;
    const rect = dropZone.getBoundingClientRect();
    const y = event.clientY - rect.top;
    const newPosition = Math.floor((y / rect.height) * this.gameState.situations.length);

    this.updateSituationPosition(this.draggedItem.id, newPosition);
  }

  updateSituationPosition(situationId: string, newPosition: number): void {
    if (!this.gameState.roomCode) return;

    this.gameService.updateSituationPosition(situationId, {
      position: newPosition,
      roomCode: this.gameState.roomCode
    }).subscribe({
      error: (error) => {
        console.error('Failed to update position:', error);
      }
    });
  }

  showResults(): void {
    if (!this.gameState.roomCode) return;

    this.isShowingResults = true;
    this.gameService.showResults(this.gameState.roomCode).subscribe({
      next: () => {
        this.gameService.updateGameState({ status: 'SHOW_RESULTS' });
      },
      error: (error) => {
        console.error('Failed to show results:', error);
        this.isShowingResults = false;
      }
    });
  }
}
