// src/app/pages/game-lobby/game-lobby.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { GameService } from '../../services/game.service';
import { SocketService } from '../../services/socket.service';
import { GameState, Player } from '../../models/game.models';

@Component({
  selector: 'app-game-lobby',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-4">
      <div class="max-w-4xl mx-auto">
        <!-- Header -->
        <div class="flex justify-between items-center mb-8">
          <div>
            <h1 class="text-3xl font-bold text-white mb-2">Game Lobby</h1>
            <div class="flex items-center space-x-4">
              <div class="bg-slate-800 px-4 py-2 rounded-lg">
                <span class="text-slate-400 text-sm">Room Code:</span>
                <span class="text-white font-mono font-bold ml-2">{{ gameState.roomCode }}</span>
              </div>
              <div class="flex items-center text-green-400" *ngIf="connected">
                <i class="fas fa-circle text-xs mr-2"></i>
                <span class="text-sm">Connected</span>
              </div>
              <div class="flex items-center text-red-400" *ngIf="!connected">
                <i class="fas fa-circle text-xs mr-2"></i>
                <span class="text-sm">Disconnected</span>
              </div>
            </div>
          </div>
          <button 
            (click)="copyRoomCode()"
            class="bg-slate-700 hover:bg-slate-600 text-white px-4 py-2 rounded-lg transition-colors"
          >
            <i class="fas fa-copy mr-2"></i>
            Copy Code
          </button>
        </div>

        <div class="grid lg:grid-cols-2 gap-8">
          <!-- Players List -->
          <div class="bg-slate-800/50 border border-slate-700 rounded-lg p-6">
            <h3 class="text-xl font-semibold text-white mb-4">
              Players ({{ gameState.players.length }})
            </h3>
            <div class="space-y-3">
              <div 
                *ngFor="let player of gameState.players"
                class="flex items-center space-x-3 p-3 bg-slate-700/50 rounded-lg"
              >
                <div 
                  class="w-4 h-4 rounded-full"
                  [style.background-color]="player.color"
                ></div>
                <span class="text-white font-medium">{{ player.name }}</span>
                <span 
                  *ngIf="player.isHost"
                  class="bg-primary/20 text-primary px-2 py-1 rounded text-xs font-medium"
                >
                  Host
                </span>
                <span 
                  *ngIf="player.id === gameState.playerId"
                  class="bg-green-500/20 text-green-400 px-2 py-1 rounded text-xs font-medium"
                >
                  You
                </span>
              </div>
            </div>
          </div>

          <!-- Game Setup -->
          <div class="bg-slate-800/50 border border-slate-700 rounded-lg p-6">
            <h3 class="text-xl font-semibold text-white mb-4">Game Setup</h3>
            
            <div *ngIf="gameState.isHost" class="space-y-4">
              <div>
                <label class="block text-white text-sm font-medium mb-2">Theme (Optional)</label>
                <input
                  [(ngModel)]="theme"
                  placeholder="e.g., Food, Movies, Travel..."
                  class="w-full px-3 py-2 bg-slate-700 border border-slate-600 text-white placeholder-slate-400 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                />
              </div>
              
              <div>
                <label class="block text-white text-sm font-medium mb-2">Custom Prompts</label>
                <div class="space-y-2">
                  <input 
                    *ngFor="let prompt of customPrompts; let i = index"
                    [(ngModel)]="customPrompts[i]"
                    placeholder="Enter a custom prompt..."
                    class="w-full px-3 py-2 bg-slate-700 border border-slate-600 text-white placeholder-slate-400 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                </div>
                <button 
                  (click)="addCustomPrompt()"
                  class="mt-2 text-primary hover:text-primary/80 text-sm"
                >
                  + Add another prompt
                </button>
              </div>

              <button 
                (click)="updateGameSetup()"
                [disabled]="isUpdating"
                class="w-full bg-slate-600 hover:bg-slate-500 text-white font-medium py-2 px-4 rounded-md transition-colors disabled:opacity-50"
              >
                <span *ngIf="isUpdating">
                  <i class="fas fa-spinner fa-spin mr-2"></i>
                  Updating...
                </span>
                <span *ngIf="!isUpdating">Update Setup</span>
              </button>

              <div class="pt-4 border-t border-slate-600">
                <button 
                  (click)="startGame()"
                  [disabled]="isStarting || gameState.players.length < 2"
                  class="w-full bg-primary hover:bg-primary/90 text-white font-medium py-3 px-4 rounded-md transition-colors disabled:opacity-50"
                >
                  <span *ngIf="isStarting">
                    <i class="fas fa-spinner fa-spin mr-2"></i>
                    Starting...
                  </span>
                  <span *ngIf="!isStarting">Start Game</span>
                </button>
                <p 
                  *ngIf="gameState.players.length < 2"
                  class="text-slate-400 text-sm text-center mt-2"
                >
                  Need at least 2 players to start
                </p>
              </div>
            </div>

            <div *ngIf="!gameState.isHost" class="text-center py-8">
              <i class="fas fa-clock text-slate-400 text-3xl mb-4"></i>
              <p class="text-slate-400">Waiting for host to start the game...</p>
            </div>
          </div>
        </div>

        <!-- Game Rules -->
        <div class="mt-8 bg-slate-800/30 border border-slate-700 rounded-lg p-6">
          <h3 class="text-lg font-semibold text-white mb-4">How to Play</h3>
          <div class="grid md:grid-cols-3 gap-4 text-sm">
            <div>
              <div class="flex items-center text-primary mb-2">
                <i class="fas fa-edit mr-2"></i>
                <span class="font-medium">1. Create</span>
              </div>
              <p class="text-slate-400">Each player creates a situation based on the prompt</p>
            </div>
            <div>
              <div class="flex items-center text-purple-400 mb-2">
                <i class="fas fa-sort mr-2"></i>
                <span class="font-medium">2. Arrange</span>
              </div>
              <p class="text-slate-400">Drag and drop situations to arrange them in order</p>
            </div>
            <div>
              <div class="flex items-center text-green-400 mb-2">
                <i class="fas fa-trophy mr-2"></i>
                <span class="font-medium">3. Score</span>
              </div>
              <p class="text-slate-400">See how well your arrangement matches the secret numbers</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .text-primary { color: hsl(263 70% 50%); }
    .bg-primary { background-color: hsl(263 70% 50%); }
    .bg-primary\\/20 { background-color: hsla(263 70% 50% / 0.2); }
  `]
})
export class GameLobbyComponent implements OnInit, OnDestroy {
  gameState!: GameState;
  connected = false;
  theme = '';
  customPrompts = [''];
  isUpdating = false;
  isStarting = false;
  
  private subscriptions = new Subscription();

  constructor(
    private gameService: GameService,
    private socketService: SocketService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.subscriptions.add(
      this.gameService.gameState$.subscribe(state => {
        this.gameState = state;
        if (!state.roomCode) {
          this.router.navigate(['/']);
          return;
        }
        
        if (state.status === 'IN_PROGRESS') {
          this.router.navigate(['/game']);
        }
        
        // Connect to WebSocket
        this.socketService.connect(state.roomCode);
      })
    );

    this.subscriptions.add(
      this.socketService.connected$.subscribe(connected => {
        this.connected = connected;
      })
    );

    // Listen for game events
    this.subscriptions.add(
      this.socketService.on('gameStarted').subscribe(() => {
        this.gameService.updateGameState({ status: 'IN_PROGRESS' });
      })
    );

    this.subscriptions.add(
      this.socketService.on('playerJoined').subscribe((player: Player) => {
        const currentPlayers = this.gameState.players;
        this.gameService.updateGameState({
          players: [...currentPlayers, player]
        });
      })
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
    this.socketService.disconnect();
  }

  copyRoomCode(): void {
    navigator.clipboard.writeText(this.gameState.roomCode || '');
    // Could add toast notification here
  }

  addCustomPrompt(): void {
    this.customPrompts.push('');
  }

  updateGameSetup(): void {
    if (!this.gameState.roomCode) return;

    this.isUpdating = true;
    const setupData = {
      theme: this.theme.trim() || undefined,
      customPrompts: this.customPrompts.filter(p => p.trim()).length > 0 
        ? this.customPrompts.filter(p => p.trim()) 
        : undefined
    };

    this.gameService.updateGameSetup(this.gameState.roomCode, setupData).subscribe({
      next: () => {
        this.isUpdating = false;
        // Could add success toast
      },
      error: (error) => {
        console.error('Failed to update setup:', error);
        this.isUpdating = false;
      }
    });
  }

  startGame(): void {
    if (!this.gameState.roomCode) return;

    this.isStarting = true;
    this.gameService.startGame(this.gameState.roomCode).subscribe({
      next: () => {
        // Socket event will handle navigation
      },
      error: (error) => {
        console.error('Failed to start game:', error);
        this.isStarting = false;
      }
    });
  }
}
<div class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-4">
  <div class="max-w-4xl mx-auto">
    <!-- Header -->
    <div class="flex justify-between items-center mb-8">
      <div>
        <h1 class="text-3xl font-bold text-white mb-2">Game Lobby</h1>
        <div class="flex items-center space-x-4">
          <div class="bg-slate-800 px-4 py-2 rounded-lg">
            <span class="text-slate-400 text-sm">Room Code:</span>
            <span class="text-white font-mono font-bold ml-2">{{ gameState.roomCode }}</span>
          </div>
          <div class="flex items-center text-green-400" *ngIf="connected">
            <i class="fas fa-circle text-xs mr-2"></i>
            <span class="text-sm">Connected</span>
          </div>
          <div class="flex items-center text-red-400" *ngIf="!connected">
            <i class="fas fa-circle text-xs mr-2"></i>
            <span class="text-sm">Disconnected</span>
          </div>
        </div>
      </div>
      <button 
        (click)="copyRoomCode()"
        class="bg-slate-700 hover:bg-slate-600 text-white px-4 py-2 rounded-lg transition-colors"
      >
        <i class="fas fa-copy mr-2"></i>
        Copy Code
      </button>
    </div>

    <div class="grid lg:grid-cols-2 gap-8">
      <!-- Players List -->
      <div class="bg-slate-800/50 border border-slate-700 rounded-lg p-6">
        <h3 class="text-xl font-semibold text-white mb-4">
          Players ({{ gameState.players.length }})
        </h3>
        <div class="space-y-3">
          <div 
            *ngFor="let player of gameState.players"
            class="flex items-center space-x-3 p-3 bg-slate-700/50 rounded-lg"
          >
            <div 
              class="w-4 h-4 rounded-full"
              [style.background-color]="player.color"
            ></div>
            <span class="text-white font-medium">{{ player.name }}</span>
            <span 
              *ngIf="player.isHost"
              class="bg-primary/20 text-primary px-2 py-1 rounded text-xs font-medium"
            >
              Host
            </span>
            <span 
              *ngIf="player.id === gameState.playerId"
              class="bg-green-500/20 text-green-400 px-2 py-1 rounded text-xs font-medium"
            >
              You
            </span>
          </div>
        </div>
      </div>

      <!-- Game Setup -->
      <div class="bg-slate-800/50 border border-slate-700 rounded-lg p-6">
        <h3 class="text-xl font-semibold text-white mb-4">Game Setup</h3>
        
        <div *ngIf="gameState.isHost" class="space-y-4">
          <div>
            <label class="block text-white text-sm font-medium mb-2">Theme (Optional)</label>
            <input
              [(ngModel)]="theme"
              placeholder="e.g., Food, Movies, Travel..."
              class="w-full px-3 py-2 bg-slate-700 border border-slate-600 text-white placeholder-slate-400 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
          
          <div>
            <label class="block text-white text-sm font-medium mb-2">Custom Prompts</label>
            <div class="space-y-2">
              <input 
                *ngFor="let prompt of customPrompts; let i = index"
                [(ngModel)]="customPrompts[i]"
                placeholder="Enter a custom prompt..."
                class="w-full px-3 py-2 bg-slate-700 border border-slate-600 text-white placeholder-slate-400 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
            <button 
              (click)="addCustomPrompt()"
              class="mt-2 text-primary hover:text-primary/80 text-sm"
            >
              + Add another prompt
            </button>
          </div>

          <button 
            (click)="updateGameSetup()"
            [disabled]="isUpdating"
            class="w-full bg-slate-600 hover:bg-slate-500 text-white font-medium py-2 px-4 rounded-md transition-colors disabled:opacity-50"
          >
            <span *ngIf="isUpdating">
              <i class="fas fa-spinner fa-spin mr-2"></i>
              Updating...
            </span>
            <span *ngIf="!isUpdating">Update Setup</span>
          </button>

          <div class="pt-4 border-t border-slate-600">
            <button 
              (click)="startGame()"
              [disabled]="isStarting || gameState.players.length < 2"
              class="w-full bg-primary hover:bg-primary/90 text-white font-medium py-3 px-4 rounded-md transition-colors disabled:opacity-50"
            >
              <span *ngIf="isStarting">
                <i class="fas fa-spinner fa-spin mr-2"></i>
                Starting...
              </span>
              <span *ngIf="!isStarting">Start Game</span>
            </button>
            <p 
              *ngIf="gameState.players.length < 2"
              class="text-slate-400 text-sm text-center mt-2"
            >
              Need at least 2 players to start
            </p>
          </div>
        </div>

        <div *ngIf="!gameState.isHost" class="text-center py-8">
          <i class="fas fa-clock text-slate-400 text-3xl mb-4"></i>
          <p class="text-slate-400">Waiting for host to start the game...</p>
        </div>
      </div>
    </div>

    <!-- Game Rules -->
    <div class="mt-8 bg-slate-800/30 border border-slate-700 rounded-lg p-6">
      <h3 class="text-lg font-semibold text-white mb-4">How to Play</h3>
      <div class="grid md:grid-cols-3 gap-4 text-sm">
        <div>
          <div class="flex items-center text-primary mb-2">
            <i class="fas fa-edit mr-2"></i>
            <span class="font-medium">1. Create</span>
          </div>
          <p class="text-slate-400">Each player creates a situation based on the prompt</p>
        </div>
        <div>
          <div class="flex items-center text-purple-400 mb-2">
            <i class="fas fa-sort mr-2"></i>
            <span class="font-medium">2. Arrange</span>
          </div>
          <p class="text-slate-400">Drag and drop situations to arrange them in order</p>
        </div>
        <div>
          <div class="flex items-center text-green-400 mb-2">
            <i class="fas fa-trophy mr-2"></i>
            <span class="font-medium">3. Score</span>
          </div>
          <p class="text-slate-400">See how well your arrangement matches the secret numbers</p>
        </div>
      </div>
    </div>
  </div>
</div>

// client/src/pages/GameLobby.tsx
import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { useGame } from '@/contexts/GameContext';
import { useSocket } from '@/hooks/useSocket';
import { PlayerCard } from '@/components/PlayerCard';

const themeOptions = [
  { value: 'life-events', label: 'Life Events', description: 'Major life milestones and experiences' },
  { value: 'historical-events', label: 'Historical Events', description: 'Important moments in history' },
  { value: 'daily-activities', label: 'Daily Activities', description: 'Common everyday situations' },
  { value: 'custom', label: 'Custom Prompts', description: 'Create your own prompt list' },
];

export default function GameLobby() {
  const [, setLocation] = useLocation();
  const { state, dispatch } = useGame();
  const { toast } = useToast();
  const { on, emit } = useSocket(state.roomCode || undefined);

  const [selectedTheme, setSelectedTheme] = useState<string>('');
  const [customPrompts, setCustomPrompts] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (!state.roomCode) {
      setLocation('/');
      return;
    }

    // Load game state
    loadGameState();

    // Socket event listeners
    const unsubscribers = [
      on('player:joined', (data: any) => {
        dispatch({ type: 'ADD_PLAYER', payload: data.player });
        toast({
          title: "Player Joined",
          description: `${data.player.name} joined the game`,
        });
      }),

      on('game:setup_updated', (data: any) => {
        toast({
          title: "Game Setup Updated",
          description: "Host updated the game configuration",
        });
      }),

      on('game:started', (data: any) => {
        dispatch({
          type: 'SET_CURRENT_ROUND',
          payload: { round: data.round, prompt: data.prompt }
        });
        dispatch({ type: 'SET_STATUS', payload: 'IN_PROGRESS' });
        setLocation('/game');
      }),
    ];

    return () => {
      unsubscribers.forEach(unsub => unsub());
    };
  }, [state.roomCode]);

  const loadGameState = async () => {
    try {
      const response = await apiRequest('GET', `/api/games/${state.roomCode}`);
      const gameData = await response.json();

      dispatch({
        type: 'SET_GAME_STATE',
        payload: {
          players: gameData.players,
          prompts: gameData.prompts,
          status: gameData.game.status,
        }
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to load game state",
        variant: "destructive",
      });
    }
  };

  const updateGameSetup = async () => {
    if (!selectedTheme) {
      toast({
        title: "Error",
        description: "Please select a theme",
        variant: "destructive",
      });
      return;
    }

    try {
      const payload: any = { theme: selectedTheme };
      
      if (selectedTheme === 'custom') {
        const promptLines = customPrompts.split('\n').filter(line => line.trim());
        if (promptLines.length < 3) {
          toast({
            title: "Error",
            description: "Please provide at least 3 custom prompts",
            variant: "destructive",
          });
          return;
        }
        payload.customPrompts = promptLines;
      }

      await apiRequest('PUT', `/api/games/${state.roomCode}/setup`, payload);
      
      toast({
        title: "Success",
        description: "Game setup updated",
      });

      // Reload prompts
      loadGameState();
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to update game setup",
        variant: "destructive",
      });
    }
  };

  const startGame = async () => {
    if (state.players.length < 2) {
      toast({
        title: "Error",
        description: "Need at least 2 players to start",
        variant: "destructive",
      });
      return;
    }

    if (state.prompts.length === 0) {
      toast({
        title: "Error",
        description: "Please configure prompts before starting",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    try {
      await apiRequest('POST', `/api/games/${state.roomCode}/start`);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to start game",
        variant: "destructive",
      });
      setIsLoading(false);
    }
  };

  const copyRoomCode = () => {
    navigator.clipboard.writeText(state.roomCode || '');
    toast({
      title: "Copied!",
      description: "Room code copied to clipboard",
    });
  };

  const copyInviteLink = () => {
    const link = `${window.location.origin}/?join=${state.roomCode}`;
    navigator.clipboard.writeText(link);
    toast({
      title: "Copied!",
      description: "Invite link copied to clipboard",
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      {/* Header */}
      <header className="bg-white/10 backdrop-blur-md border-b border-white/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center space-x-3">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setLocation('/')}
                className="text-white hover:bg-white/10"
              >
                <i className="fas fa-arrow-left mr-2"></i>
                Back
              </Button>
              <h1 className="text-2xl font-bold text-white">Game Lobby</h1>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2 text-white/70">
                <i className="fas fa-users text-sm"></i>
                <span className="text-sm">{state.players.length} players</span>
              </div>
              <div className="bg-white/20 backdrop-blur px-3 py-1 rounded-full">
                <span className="text-white text-sm font-medium">{state.status}</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Room Info Card */}
        <Card className="bg-white/10 backdrop-blur-md border-white/20 mb-8">
          <CardContent className="p-6">
            <div className="flex flex-col lg:flex-row lg:justify-between lg:items-center space-y-4 lg:space-y-0">
              <div>
                <h2 className="text-2xl font-bold text-white mb-2">Game Lobby</h2>
                <div className="flex items-center space-x-4 text-white/70">
                  <div className="flex items-center space-x-2">
                    <i className="fas fa-key"></i>
                    <span className="font-mono text-lg">{state.roomCode}</span>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={copyRoomCode}
                      className="text-primary hover:text-primary/80"
                    >
                      <i className="fas fa-copy"></i>
                    </Button>
                  </div>
                  <div className="w-px h-6 bg-white/30"></div>
                  <span>{state.players.length} players joined</span>
                </div>
              </div>
              
              <div className="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-3">
                <Button
                  variant="outline"
                  onClick={copyInviteLink}
                  className="bg-white/20 hover:bg-white/30 border-white/20 text-white"
                >
                  <i className="fas fa-share mr-2"></i>
                  Share Invite
                </Button>
                {state.isHost && (
                  <Button
                    onClick={startGame}
                    disabled={isLoading || state.players.length < 2 || state.prompts.length === 0}
                    className="bg-gradient-to-r from-primary to-purple-500 hover:from-primary/90 hover:to-purple-500/90"
                  >
                    {isLoading ? (
                      <>
                        <i className="fas fa-spinner fa-spin mr-2"></i>
                        Starting...
                      </>
                    ) : (
                      <>
                        <i className="fas fa-play mr-2"></i>
                        Start Game
                      </>
                    )}
                  </Button>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Players List */}
          <div className="lg:col-span-2">
            <Card className="bg-white/10 backdrop-blur-md border-white/20">
              <CardHeader>
                <CardTitle className="text-white flex items-center space-x-2">
                  <i className="fas fa-users"></i>
                  <span>Players</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {state.players.map((player) => (
                    <PlayerCard key={player.id} player={player} />
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Game Setup Panel */}
          <div className="space-y-6">
            {/* Theme Selection */}
            {state.isHost && (
              <Card className="bg-white/10 backdrop-blur-md border-white/20">
                <CardHeader>
                  <CardTitle className="text-white flex items-center space-x-2">
                    <i className="fas fa-palette"></i>
                    <span>Theme</span>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Select value={selectedTheme} onValueChange={setSelectedTheme}>
                    <SelectTrigger className="bg-white/10 border-white/20 text-white">
                      <SelectValue placeholder="Select a theme..." />
                    </SelectTrigger>
                    <SelectContent>
                      {themeOptions.map((theme) => (
                        <SelectItem key={theme.value} value={theme.value}>
                          <div>
                            <div className="font-medium">{theme.label}</div>
                            <div className="text-sm text-muted-foreground">{theme.description}</div>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  {selectedTheme === 'custom' && (
                    <div>
                      <Label htmlFor="customPrompts" className="text-white">
                        Custom Prompts (one per line)
                      </Label>
                      <Textarea
                        id="customPrompts"
                        value={customPrompts}
                        onChange={(e) => setCustomPrompts(e.target.value)}
                        placeholder="Enter prompts, one per line..."
                        className="bg-white/10 border-white/20 text-white placeholder-white/50"
                        rows={5}
                      />
                    </div>
                  )}

                  <Button
                    onClick={updateGameSetup}
                    disabled={!selectedTheme}
                    className="w-full bg-primary hover:bg-primary/90"
                  >
                    Update Setup
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* Prompts Preview */}
            <Card className="bg-white/10 backdrop-blur-md border-white/20">
              <CardHeader>
                <CardTitle className="text-white flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <i className="fas fa-list-ul"></i>
                    <span>Prompts</span>
                  </div>
                  <Badge variant="secondary">{state.prompts.length}</Badge>
                </CardTitle>
              </CardHeader>
              <CardContent>
                {state.prompts.length > 0 ? (
                  <div className="space-y-2 max-h-48 overflow-y-auto">
                    {state.prompts.map((prompt, index) => (
                      <div key={prompt.id} className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                        <span className="text-white/80 text-sm">{prompt.text}</span>
                        <Badge variant="outline" className="text-xs">
                          {index + 1}
                        </Badge>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8 text-white/60">
                    <i className="fas fa-list-ul text-3xl mb-2 opacity-50"></i>
                    <p>No prompts configured yet</p>
                    {state.isHost && <p className="text-sm">Select a theme to add prompts</p>}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
